# Generated by Django 6.0 on 2025-12-27 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
    ]
